### PR TITLE
Check if objective is null before checking its name

### PR DESCRIPTION
**Pull request by iPyronic**

### CODE REVIEW

**Comment by games647** [comment]
Please provide a reason for this change.

**Comment by iPyronic** [comment]
Someone on the Spigot forums had a thread and was asking about the errors he/she had in their server log. One of the errors was in ScoreboardStats: http://pastebin.com/SfKLQ84u

The objective will be null if the player doesn't have anything in their sidebar, right? So it should probably be checked before trying to compare the name.

I kinda don't know how to use github correctly though... so I'm guessing I did this pull request wrong o.o

**Comment by games647** [comment]
No it's ok. I thought this shouldn't happen, because it's already checked [here](https://github.com/games647/ScoreboardStats/blob/master/src/main/java/com/github/games647/scoreboardstats/BukkitScoreboardManager.java#L84).

In the error you posted. A new scoreboard is created and should be available so. Maybe another plugin modifies the scoreboards async? Could you post the link to the thread?

**Comment by iPyronic** [comment]
Sure, this is the thread: https://www.spigotmc.org/threads/world-file-error.97155/

The person didn't post the full server log though, so there isn't a list of their plugins :/

The log that was posted contained this error in ScoreboardStats twice, and I'm guessing they were both about a minute apart (although the first one is missing the time).

By the way, I noticed the latest version on bukkit is 0.9.1, but the github says 0.9.3, dunno if that changes anything relevant though.

**Comment by games647** [comment]
Interesting... I found that [TeamPvP](http://dev.bukkit.org/bukkit-plugins/teampvp/) uses sidebar scoreboards too, but this plugins also runs sync (as far as I know). 
According to the log the sidebar objective was null and then ScoreboardStats created a new objective. Only on success it **should** call the method sendUpdate(Player, boolean). So I think there are async modifications.

>By the way, I noticed the latest version on bukkit is 0.9.1, but the github says 0.9.3, dunno if that changes anything relevant though.

But I guess there are no changes relevant to this.

Anyways a null-check is always a good practise.

**Pull request merged**
